# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(default=b'', max_length=30)),
                ('browser', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('job', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('game', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
